### PR TITLE
auto convert expressions to calls (Issue #52)

### PR DESCRIPTION
**Pull request by jakob-r**

### CODE REVIEW

**Comment by berndbischl** [comment]
NEWS: 
make*Param argument 'requires' now accepts expressions and quote'd expressions.

**Comment by berndbischl** [comment]
we need to carefully update docs now.
AND check whether we need to update something in mlr

**Comment by jakob-r** [comment]
I don't know why this does not base on master. I will fix it

**Comment by jakob-r** [comment]
okay - fixed

**Comment by berndbischl** [comment]
i have made the docs and test better and updated also NEWS

**Pull request merged**
