### PR TITLE
allow ph to use expressions in the parameters

### PR DESCRIPTION
**Pull request by kerschke**
- ParamHelpers is now able to handle expressions in the following arguments of a parameter: `len`, `lower`, `upper`, `default` and `values`
- one can make a feasibility check of the ParamSet at the time of creation by defining a character vector `dictionary`
- if the ParamSet only consists of LearnerParams, it will inherit the additional class label `LearnerParamSet` and the typical mlr-dictionary, i.e. `task`, `type`, `k`, `p` and `n`
- one can evaluate the entire ParamSet given an environment or list via `evaluateParamSet`
- the ParamSets can also be checked with `checkParamSet` (which basically evaluates the expressions and then sanity checks the defaults, boundaries and values)

In principle this can now be employed by mlr.. However, there are still some bugs when using it with mlr. I will post more details in the issue tracker in a few minutes..

### CODE REVIEW

**Comment by kerschke** [comment]
Could you re-run the Travis build? On my computer, I do not get any errors and just one warning:
```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'getParamSet'
  ‘...’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```

Apart from that, it should run without any problems..

**Comment by jakobbossek** [comment]
Rerunning will fail as well since `warnings_are_errors` is `TRUE` on travis for PH.

**Comment by berndbischl** [comment]
Michel forgot to fix this, when he pushed in to master.
@mllg 
He then fixed it, I reverted this now. I will answer in the thread here
https://github.com/jakobbossek/smoof/issues/73

**Comment by berndbischl** [comment]
Conclusion now here: PH should cleanly runs through the checks in master

**Comment by kerschke** [comment]
@mllg: I've rebased the "expression"-branch in my fork and also wrapped 'print' around the 1st arguments of all expect_output tests. Now, I still have warnings, which can basically be grouped into the following two cases:
- generateDesign produces less points than defined by its arguments (occurs within test_forbidden and test_generateDesign)
- lots of warnings when testing test_renderOptPathPlot

As far as I can tell, none of these issues is influenced by any of my functions, but for now, I apparently can't test my commits (via travis).. Any suggestions how to fix that?

**Comment by mllg** [comment]
I'll have a look tomorrow. In the meantime, could you please have a closer look at the vignettes of [lazyeval](https://cran.r-project.org/web/packages/lazyeval/index.html) and figure out if we want to use it?

**Comment by mllg** [comment]
If possible, try your best to rebase on master. If something terrible happens, we will do this "manually" together tomorrow, but please give it a shot.

**Comment by kerschke** [comment]
Ok, I'll have a look at it - but probably not before tomorrow morning.. Otherwise, I'm really going to break something ;-)

**Pull request closed without merging**
