### PR TITLE
generateRandomDesign keeps factor order and cleanup of generateDesign

### PR DESCRIPTION
**Pull request by jakob-r**
It could happen that generateRandomDesign mixed up the orders of the factors. This is now fixed. In the process I also cleaned generateDesign a tiny bit.
I introduced the unexported function getParamSetValues as a helper.

### CODE REVIEW

**Comment by berndbischl** [comment]
Ok, good if that was a bug and is now fixed.
But most importantly: can you please always in these cases also push a reproducing example as a unit test? I would also like to see what was wrong before though this.
(and we need it anyhow to test for this)
thx.

**Comment by jakob-r** [comment]
The rbind was messing up the order of the factor levels. So you could have had `"a" "b"` sometimes as well as `"b" "a"`. I will try to add a test - although it obviously depends on the seed.

**Comment by jakob-r** [comment]
I seriously don't know how the coverage went down because of my changes.

**Comment by berndbischl** [comment]
> I seriously don't know how the coverage went down because of my changes.

We are at 97% .Who cares, as long as we handle this with intelligence.

**Comment by jakob-r** [comment]
I just thought that this is an indicator that something strange/not expected happens.

**Comment by berndbischl** [comment]
Summary of talk with Jakob on hangout:

1) Sometimes the order of the factor levels in the resulting design was messed up. Either the levels were permuted or empty one were dropped.

2) Conclusion is: 
- we keep the levels, exactly as in the par.set
- if the user wants to drop the empty ones, droplevels exists
- as we have that , we dont need an option to drop levels.

3) The last point above is a bit unclear. If we now break code, because we generate too many levels, we might have to have that option. 

Hmmm. Still not sure. maybe to have the option, and even set it to drop.levels = TRUE is better?
Then the data.frame is nice to work with, we don't break code, and still the user can access all info if we chooses to?

I guess the main question is, whether one USUALLY want empty levels or not?

Sorry, I dont want to overcomplicate this, but this function we use very often now, and it should be "perfect".

**Comment by jakob-r** [comment]
To simplify it. I didn't change too much. The behaviour of `generateDesign` didn't change at all. In fact, I adapted the behaviour of `generateRandomDesign` and `generateGridDesign` to the former as this is the most often used design-function. Anyhow, if we generate a Design with empty levels we are more or less broken nonetheless and in some kind of special case.

**Comment by jakob-r** [comment]
*ping*

**Pull request merged**
