### PR TITLE
better getters for type strings, they are exported now

### PR DESCRIPTION
**Pull request by berndbischl**
NEWS:
- new functions
-- getTypeStringsNumeric, getTypeStringsDiscrete

### CODE REVIEW

**Comment by berndbischl** [comment]
@jakob-r 
please review and merge soon

**Comment by jakob-r** [comment]
Looks fine, merged

**Comment by berndbischl** [comment]
arghhhh there was a supid type

**Comment by berndbischl** [comment]
ok i will fix this in master now. please wait 5 min

**Comment by berndbischl** [comment]
ok, i resolved this in master now. there was an "s" missing in getTypeStringsDiscrete

**Pull request merged**
