### PR TITLE
is feasible and requirements jumble

### PR DESCRIPTION
**Pull request by jakob-r**

### CODE REVIEW

**Comment by jakob-r** [comment]
I would love to Merge this some day. Was some work.

**Comment by jakob-r** [comment]
**ping**

**Comment by jakob-r** [comment]
@mllg thanks for checking!
We might have a problem with the changed behavior of `getParamTypes` ? I will rebase and check.

**Comment by mllg** [comment]
I reviewed most of the code and added a test. Functions and arguments may be awkwardly named still. Your turn, Bernd.

**Comment by jakob-r** [comment]
We did a reverse dependency check and only mlr failed so I did it manually, simply with `rtest` and an install of ParamHelpers and this specific branch. There were no ParamHelper relevant Errors.

**Comment by jakob-r** [comment]
*ping*

**Pull request merged**
