### PR TITLE
allow dict to be passed in hasFiniteBoxConstraints

### PR DESCRIPTION
**Pull request by jakob-r**

### CODE REVIEW

**Comment by berndbischl** [comment]
why are we passing down the dict to the parset? shouldnt the dict be ATTACHED to the parset?

**Comment by berndbischl** [comment]
ok, that is not your fault. but it seems a wrong design decision.

i will open another issue.

**Comment by berndbischl** [comment]
otherwise looks good, pls merge when green

**Comment by jakob-r** [comment]
But the content of the dict will always be different depending eg. on the Task.

**Comment by berndbischl** [comment]
> But the content of the dict will always be different depending eg. on the Task.

i openend this #175 
(but i think i am wrong and you are right, reacted too quickly)

**Pull request merged**
