### PR TITLE
correct namespace

### PR DESCRIPTION
**Pull request by jakob-r**
Solves Issue #191
Actually work of @mllg

### CODE REVIEW

**Comment by jakob-r** [comment]
@berndbischl I think you should merge this.

**Comment by rcannood** [comment]
@berndbischl Could you please have a look at this?

**Comment by jakob-r** [comment]
@berndbischl ping

**Comment by rcannood** [comment]
@berndbischl I'm still actively hoping for this simple pull request to get reviewed and merged. #191 has already given me many headaches.

**Comment by jakob-r** [comment]
@berndbischl - will auto merge in 2 days if no objection is given

**Comment by rcannood** [comment]
This is fantastic news!

**Comment by rcannood** [comment]
Thank you so much @jakob-r @mllg !!

**Pull request merged**
