### PR TITLE
fix opt path trafo bug, fixes #120

### LINKED ISSUE #120: trafoOptPath silently drops error msg, exec time
When calling `trafoOptPath` on a tune result, error.msg and exec.time are silently dropped. Looks like this is due to the default arguments for `OptPathDF`. Perhaps this should be added as an argument in case the user wants to keep these?

### PR DESCRIPTION
**Pull request by berndbischl**
@jakob-r 
hey boss pls review

### CODE REVIEW

**Comment by jakob-r** [comment]
The only thing I don't like is that this breaks compatibility with a possible other OptPathApi (like the data base approach). We would need geter for those things.

**Comment by jakob-r** [comment]
But of course you can name it `trafoOptPathDF` :wink:

**Comment by berndbischl** [comment]
> The only thing I don't like is that this breaks compatibility with a possible other OptPathApi (like the data base approach). We would need geter for those things.

if you are referring to this line: 
  # FIXME: this only works for the DF implementation!

this was there before this PR. also its not very hard to refactor this later. but at the moment we simply support only one backend.

**Comment by berndbischl** [comment]
> But of course you can name it trafoOptPathDF

no, the could thing about OO is that we can simply refactor this later, completely internally in PH.
and it will be transparent for all users. The implementing method for the trafoOptPath mechanism is then selected by S3.

**Comment by jakob-r** [comment]
Agreed. I was just hoping we don't have to specialize so many functions for different back ends. After all I want to copy the opt path and just change some values is a pretty common case which should may be have an own function. But we can do this later.

**Pull request merged**
