### PR TITLE
add default design generation

### PR DESCRIPTION
**Pull request by ja-thomas**
This is a bit simpler solution.

We just generate a param set with one row so that we can merge it by hand with other designs by hand.

### CODE REVIEW

**Comment by berndbischl** [comment]
1) why dont you call trafoValue on the "defaults" list? much simpler code!

2) Pls create a helper function to convert a list of values to a data.frame row. 
(2nd part of your code)
this is basically the opposite of dfRowsToList. and seems to be needed often so we should encapsulate this code

**Comment by berndbischl** [comment]
(otherwise looks quite nice)

**Comment by jakob-r** [comment]
Isn't `listToDfOneRow.R` better suited for BBmisc? (which we should call MOmisc (mlr-org misc))

**Comment by berndbischl** [comment]
> Isn't listToDfOneRow.R better suited for BBmisc? (which we should call MOmisc (mlr-org misc))

we could put it there later. at the very least it should not be exported in PH.

in general i would really like to redesign BBmisc (a lot?) at some point (but: time.....)

**Comment by jakob-r** [comment]
Looks good to me.

**Comment by berndbischl** [comment]
i have rewritten the code.

please try to test it more:
1) what happens if default is numeric, param is int. is the int type correct in des?
2) what happens if we have special vals? i guess it wont work, throw an error
3) what happens if the default is the name of a discrete level? or the value? how is the semantic here?

**Comment by berndbischl** [comment]
and try to finish it quickly

**Comment by berndbischl** [comment]
@ja-thomas

**Comment by ja-thomas** [comment]
1. + 2. done
I added a helper function to utils to ensure and convert the types of columns in a design in utils.R
Special values as defaults don't work, so we throw an appropriat error message

3
I'm not sure what you mean, discrete values are handles and tested. Can you say precisely what should be testet?

**Pull request merged**
