### PR TITLE
throw error if 'extras' enabled, but none passed to addOptPathEl

### PR DESCRIPTION
**Pull request by jakobbossek**
See #90. Merge if you like. Otherwise refuse :wink:

### CODE REVIEW

**Comment by jakob-r** [comment]
I like :+1:. Hopefully nobody is bothered by the small refacorizations i put in.

**Comment by jakob-r** [comment]
ping

**Comment by berndbischl** [comment]
see my comment in the issue, i dont like this so much.

**Comment by jakob-r** [comment]
Why was #124 necessary if we had this?

**Comment by berndbischl** [comment]
because i was totally confused!

like i said in the beginning i wanted to handle this differently but in the end could not. then i totally forgot about this :(

i will see if there is anything in this PR that we can still use / was not covered by our push, and then close this. i guess the code is nearly equivalent...

**Comment by berndbischl** [comment]
@ja-thomas 

do you see any differences in this code to what you did yesterday?

**Comment by ja-thomas** [comment]
I think it does the same (the reordering of the checks is a bit shorten than what we did, but I think it shouldnt matter). The added note in the description is good, maybe we should add that as well.

**Comment by berndbischl** [comment]
please do that, then we can close here. the note you could fix in master

**Comment by ja-thomas** [comment]
done

**Pull request closed without merging**
