### PR TITLE
plotOptPath and renderOptPathPlots now have nicely aligend plots

### LINKED ISSUE #78: fix alignment problem of optPath plots
Using `gridExtra:.grid.arrange` to combine ggplots works fine, but in the case of different scales of numbers on the y-axis the plots are of unequal width, which looks a little bit ugly.

See [the reported mlrMBO issue](https://github.com/mlr-org/mlrMBO/issues/109) for the solution.

### PR DESCRIPTION
**Pull request by jakobbossek**
Fixes #78 (see also the [relating mlrMBO issue](https://github.com/mlr-org/mlrMBO/issues/109)).

### CODE REVIEW

**Comment by jakob-r** [comment]
Nicely seperated procedure and documented. Looks fine to me but you wrote

> the alignment procedure fails if there is at least one plot with facets!

How does it exactly fail? Don't we have one plot with facets?

**Comment by jakobbossek** [comment]
See the constructed example in [the mlrMBO issue](https://github.com/mlr-org/mlrMBO/issues/109) for a demonstration of how everything is messed up in case of faceted plots.
We do not have faceted plots in ParamHelpers.

**Comment by jakob-r** [comment]
Ah, thanks for enlighten me :bulb: again.

**Comment by jakobbossek** [comment]
:wink:

**Comment by jakob-r** [comment]
Plots look good so far I can see it. Can be merged.

**Pull request merged**
